# Kubernetes Secrets 예제 파일
# 실제 사용 시 base64로 인코딩된 값을 입력해야 합니다.
# 
# base64 인코딩 방법:
# echo -n "your-value" | base64
# 
# 이 파일은 민감한 정보를 포함하므로 절대 Git에 커밋하지 마세요!
# 
# 생성 방법:
# kubectl create secret generic softsoul-api-secrets \
#   --from-literal=notion-api-key=YOUR_NOTION_API_KEY \
#   --from-literal=customer-data=YOUR_CUSTOMER_DATA \
#   --from-literal=exchange-data=YOUR_EXCHANGE_DATA \
#   --from-literal=external-id-data=YOUR_EXTERNAL_ID_DATA \
#   --from-literal=fund-data=YOUR_FUND_DATA \
#   --from-literal=level-database=YOUR_LEVEL_DATABASE \
#   --from-literal=myanmar-delivery-data=YOUR_MYANMAR_DELIVERY_DATA \
#   --from-literal=product-data=YOUR_PRODUCT_DATA \
#   --from-literal=shipping-data=YOUR_SHIPPING_DATA \
#   --from-literal=transaction-database=YOUR_TRANSACTION_DATABASE \
#   --from-literal=vendor-data=YOUR_VENDOR_DATA \
#   --from-literal=warehouse-data=YOUR_WAREHOUSE_DATA

apiVersion: v1
kind: Secret
metadata:
  name: softsoul-api-secrets
type: Opaque
data:
  # 아래 값들을 base64로 인코딩하여 입력하세요
  notion-api-key: <BASE64_ENCODED_VALUE>
  customer-data: <BASE64_ENCODED_VALUE>
  exchange-data: <BASE64_ENCODED_VALUE>
  external-id-data: <BASE64_ENCODED_VALUE>
  fund-data: <BASE64_ENCODED_VALUE>
  level-database: <BASE64_ENCODED_VALUE>
  myanmar-delivery-data: <BASE64_ENCODED_VALUE>
  product-data: <BASE64_ENCODED_VALUE>
  shipping-data: <BASE64_ENCODED_VALUE>
  transaction-database: <BASE64_ENCODED_VALUE>
  vendor-data: <BASE64_ENCODED_VALUE>
  warehouse-data: <BASE64_ENCODED_VALUE>

